name: Run tests on any branch push
on: [ push ]
jobs:
  clojure:
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v1
        with: { java-version: 1.11 }

#      - uses: DeLaGuardo/setup-clj-kondo@v1
#        with: { version: '2020.04.05' }

#      - name: Run clj-kondo on ubuntu
#        if: matrix.os == 'Linux'
#        run: clj-kondo --lint deps.edn

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.2
        with: { cli: 1.10.3.822 }

      - name: Tests [Linux, MacOS]
        if: ${{ matrix.os != 'windows-latest' }}
        run: clojure -M:dev:test:run-tests
        shell: bash

      - name: Tests [Windows]
        if: ${{ matrix.os == 'windows-latest' }}
        run: clojure -M:dev:test:run-tests
        shell: powershell
